// <auto-generated />
using Authentication_And_Authorization_In_Dot_Net_Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Authentication_And_Authorization_In_Dot_Net_Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Authentication_And_Authorization_In_Dot_Net_Core.Models.Boss", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Email");

                    b.ToTable("boss");
                });

            modelBuilder.Entity("Authentication_And_Authorization_In_Dot_Net_Core.Models.Employee", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(30)");

                    b.HasKey("Email");

                    b.ToTable("employee");
                });
#pragma warning restore 612, 618
        }
    }
}
